export const API = {
    AUTH: {
        REGISTER: "/api/v1/auth/register",
        LOGIN: "/api/v1/auth/login",
        REFRESH: "/api/v1/auth/refresh",
        LOGOUT: "/api/v1/auth/logout",
        WHOAMI: "/api/v1/auth/whoami",
        UPDATE: "/api/v1/auth/update",
        SEND_VERIFICATION: "/api/v1/auth/send-verification",
        VERIFY_EMAIL: "/api/v1/auth/verify-email",
        GOOGLE: "/api/v1/auth/google",
        FORGOT_PASSWORD: "/api/v1/auth/forgot-password",
        RESET_PASSWORD: "/api/v1/auth/reset-password",
    },
    ADMIN: {
        USERS: "/api/v1/admin/users",
        USER: (id: string) => `/api/v1/admin/users/${id}`,
        STATS: "/api/v1/admin/stats",
        DASHBOARD: "/api/v1/admin/dashboard",
        INCIDENTS: "/api/v1/admin/incidents",
        INCIDENT: (id: string) => `/api/v1/admin/incidents/${id}`,
        ALERTS: "/api/v1/admin/alerts",
        ALERT: (id: string) => `/api/v1/admin/alerts/${id}`,
        ALERT_RESOLVE: (id: string) => `/api/v1/admin/alerts/${id}/resolve`,
        ACTIVITIES: "/api/v1/admin/activities",
        ANALYTICS: "/api/v1/admin/analytics",
        SETTINGS: "/api/v1/admin/settings",
        AUDIT_LOGS: "/api/v1/admin/audit-logs",
        AUDIT_LOGS_STATS: "/api/v1/admin/audit-logs/stats",
    },
    DEVICES: {
        REGISTER: "/api/v1/devices/register",
        LIST: "/api/v1/devices",
        REMOVE: "/api/v1/devices/remove",
    },
};
